//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LJH.GeneralLibrary.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LJH.GeneralLibrary.Resources.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 澳门币10元 的本地化字符串。
        /// </summary>
        internal static string BillValidator_MOP10 {
            get {
                return ResourceManager.GetString("BillValidator_MOP10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 澳门币100元 的本地化字符串。
        /// </summary>
        internal static string BillValidator_MOP100 {
            get {
                return ResourceManager.GetString("BillValidator_MOP100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 澳门币20元 的本地化字符串。
        /// </summary>
        internal static string BillValidator_MOP20 {
            get {
                return ResourceManager.GetString("BillValidator_MOP20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 澳门币50元 的本地化字符串。
        /// </summary>
        internal static string BillValidator_MOP50 {
            get {
                return ResourceManager.GetString("BillValidator_MOP50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无纸币信息 的本地化字符串。
        /// </summary>
        internal static string BillValidator_NoBillInfo {
            get {
                return ResourceManager.GetString("BillValidator_NoBillInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应收费用 的本地化字符串。
        /// </summary>
        internal static string EpsonMT532_Accounts {
            get {
                return ResourceManager.GetString("EpsonMT532_Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}小时{1}分钟 的本地化字符串。
        /// </summary>
        internal static string EpsonMT532_Bill_ParkInterval {
            get {
                return ResourceManager.GetString("EpsonMT532_Bill_ParkInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡片编号 的本地化字符串。
        /// </summary>
        internal static string EpsonMT532_CardID {
            get {
                return ResourceManager.GetString("EpsonMT532_CardID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车牌号码 的本地化字符串。
        /// </summary>
        internal static string EpsonMT532_CarPlate {
            get {
                return ResourceManager.GetString("EpsonMT532_CarPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收费车型 的本地化字符串。
        /// </summary>
        internal static string EpsonMT532_CarType {
            get {
                return ResourceManager.GetString("EpsonMT532_CarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纸币数量 的本地化字符串。
        /// </summary>
        internal static string EpsonMT532_Cash {
            get {
                return ResourceManager.GetString("EpsonMT532_Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 张 的本地化字符串。
        /// </summary>
        internal static string EpsonMT532_CashCountUnit {
            get {
                return ResourceManager.GetString("EpsonMT532_CashCountUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 元 的本地化字符串。
        /// </summary>
        internal static string EpsonMT532_CashUnit {
            get {
                return ResourceManager.GetString("EpsonMT532_CashUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应找零金额 的本地化字符串。
        /// </summary>
        internal static string EpsonMT532_Change {
            get {
                return ResourceManager.GetString("EpsonMT532_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收费时间 的本地化字符串。
        /// </summary>
        internal static string EpsonMT532_ChargeDateTime {
            get {
                return ResourceManager.GetString("EpsonMT532_ChargeDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结账金额 的本地化字符串。
        /// </summary>
        internal static string EpsonMT532_CheckoutAmount {
            get {
                return ResourceManager.GetString("EpsonMT532_CheckoutAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结账小票 的本地化字符串。
        /// </summary>
        internal static string EpsonMT532_CheckoutBill {
            get {
                return ResourceManager.GetString("EpsonMT532_CheckoutBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结账时间 的本地化字符串。
        /// </summary>
        internal static string EpsonMT532_CheckoutDateTime {
            get {
                return ResourceManager.GetString("EpsonMT532_CheckoutDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结账人员 的本地化字符串。
        /// </summary>
        internal static string EpsonMT532_CheckoutOperator {
            get {
                return ResourceManager.GetString("EpsonMT532_CheckoutOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剩余硬币 的本地化字符串。
        /// </summary>
        internal static string EpsonMT532_Coin {
            get {
                return ResourceManager.GetString("EpsonMT532_Coin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个 的本地化字符串。
        /// </summary>
        internal static string EpsonMT532_CoinUnit {
            get {
                return ResourceManager.GetString("EpsonMT532_CoinUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常描述 的本地化字符串。
        /// </summary>
        internal static string EpsonMT532_Description {
            get {
                return ResourceManager.GetString("EpsonMT532_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入场时间 的本地化字符串。
        /// </summary>
        internal static string EpsonMT532_EnterDateTime {
            get {
                return ResourceManager.GetString("EpsonMT532_EnterDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已找零金额 的本地化字符串。
        /// </summary>
        internal static string EpsonMT532_HadChange {
            get {
                return ResourceManager.GetString("EpsonMT532_HadChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经收取 的本地化字符串。
        /// </summary>
        internal static string EpsonMT532_HavePaid {
            get {
                return ResourceManager.GetString("EpsonMT532_HavePaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收入金额 的本地化字符串。
        /// </summary>
        internal static string EpsonMT532_IncomeMoney {
            get {
                return ResourceManager.GetString("EpsonMT532_IncomeMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上次结余 的本地化字符串。
        /// </summary>
        internal static string EpsonMT532_LastBalance {
            get {
                return ResourceManager.GetString("EpsonMT532_LastBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上次结账 的本地化字符串。
        /// </summary>
        internal static string EpsonMT532_LastDateTime {
            get {
                return ResourceManager.GetString("EpsonMT532_LastDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缴费机号 的本地化字符串。
        /// </summary>
        internal static string EpsonMT532_MID {
            get {
                return ResourceManager.GetString("EpsonMT532_MID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收费人员 的本地化字符串。
        /// </summary>
        internal static string EpsonMT532_Operator {
            get {
                return ResourceManager.GetString("EpsonMT532_Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本次收取 的本地化字符串。
        /// </summary>
        internal static string EpsonMT532_Paid {
            get {
                return ResourceManager.GetString("EpsonMT532_Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实缴费用 的本地化字符串。
        /// </summary>
        internal static string EpsonMT532_PaidIn {
            get {
                return ResourceManager.GetString("EpsonMT532_PaidIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停车时长 的本地化字符串。
        /// </summary>
        internal static string EpsonMT532_ParkInterval {
            get {
                return ResourceManager.GetString("EpsonMT532_ParkInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 临时卡缴费小票 的本地化字符串。
        /// </summary>
        internal static string EpsonMT532_PaymentBill {
            get {
                return ResourceManager.GetString("EpsonMT532_PaymentBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 支出金额 的本地化字符串。
        /// </summary>
        internal static string EpsonMT532_PayMoney {
            get {
                return ResourceManager.GetString("EpsonMT532_PayMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 充值金额 的本地化字符串。
        /// </summary>
        internal static string EpsonMT532_Recharge_Amount {
            get {
                return ResourceManager.GetString("EpsonMT532_Recharge_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡片余额 的本地化字符串。
        /// </summary>
        internal static string EpsonMT532_Recharge_Balance {
            get {
                return ResourceManager.GetString("EpsonMT532_Recharge_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 充值小票 的本地化字符串。
        /// </summary>
        internal static string EpsonMT532_Recharge_Bill {
            get {
                return ResourceManager.GetString("EpsonMT532_Recharge_Bill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 充值后余额 的本地化字符串。
        /// </summary>
        internal static string EpsonMT532_Recharge_ChargeBalance {
            get {
                return ResourceManager.GetString("EpsonMT532_Recharge_ChargeBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 充值时间 的本地化字符串。
        /// </summary>
        internal static string EpsonMT532_Recharge_DateTime {
            get {
                return ResourceManager.GetString("EpsonMT532_Recharge_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 充值编号 的本地化字符串。
        /// </summary>
        internal static string EpsonMT532_Recharge_Number {
            get {
                return ResourceManager.GetString("EpsonMT532_Recharge_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实收金额 的本地化字符串。
        /// </summary>
        internal static string EpsonMT532_Recharge_Payment {
            get {
                return ResourceManager.GetString("EpsonMT532_Recharge_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缴费编号 的本地化字符串。
        /// </summary>
        internal static string EpsonMT532_SerialNumber {
            get {
                return ResourceManager.GetString("EpsonMT532_SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收费站点 的本地化字符串。
        /// </summary>
        internal static string EpsonMT532_StationID {
            get {
                return ResourceManager.GetString("EpsonMT532_StationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收费类型 的本地化字符串。
        /// </summary>
        internal static string EpsonMT532_TariffType {
            get {
                return ResourceManager.GetString("EpsonMT532_TariffType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本次结余 的本地化字符串。
        /// </summary>
        internal static string EpsonMT532_TheBalance {
            get {
                return ResourceManager.GetString("EpsonMT532_TheBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 钱箱总额 的本地化字符串。
        /// </summary>
        internal static string EpsonMT532_TotalAmount {
            get {
                return ResourceManager.GetString("EpsonMT532_TotalAmount", resourceCulture);
            }
        }
    }
}
